version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=dspa
      - DB_NAME=dspasample
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dspa
      MYSQL_DATABASE: dspasample
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dspasample_dump.sql:/docker-entrypoint-initdb.d/dspasample_dump.sql

volumes:
  mysql-data:
