version: '3.8'

services:
  app:
    image: elenakrismer/dspa-main-app:latest
    command: ["node", "index.mjs"]
    ports:
      - "443:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=dspa
      - DB_NAME=dynaprotdb
      - DB_PORT=3306
    depends_on:
      - mysql
    volumes:
      - ./certs/nginx.key:/usr/src/app/nginx.key
      - ./certs/nginx.crt:/usr/src/app/nginx.crt

  mysql:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dspa
      MYSQL_DATABASE: dynaprotdb
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql-data:/var/lib/mysql
      - ./dynaprotdb.sql:/docker-entrypoint-initdb.d/dynaprotdb.sql

volumes:
  mysql-data: