version: '3.8'

services:
  webapp:
    image: elenakrismer/dspa-main-app:latest
    networks:
      - webnet
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=dynaprot.org,www.dynaprot.org
      - LETSENCRYPT_HOST=dynaprot.org,www.dynaprot.org
      - LETSENCRYPT_EMAIL=elena.krismer@gmail.com
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=dspa
      - DB_NAME=dynaprotdb
      - DB_PORT=3306


  db:
    image: mysql:8.0
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: dspa
      MYSQL_DATABASE: dynaprotdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dynaprotdb.sql:/docker-entrypoint-initdb.d/dynaprotdb.sql

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - webnet
    environment:
      - NGINX_PROXY_CONTAINER=ekrismer-nginx-proxy-1 

networks:
  webnet:

volumes:
  mysql-data:
